import { useState } from 'react'
import { useLang } from '../../context/LanguageContext'

export default function CareerPathway({standalone=false}:{standalone?:boolean}) {
 const Heading=standalone?'h1':'h2'
  const { lang } = useLang()
  const t = (en: string, pt: string) => lang === 'pt' ? pt : en
  const [years, setYears] = useState(3)
  const cards = [
    { title: t('Spring week / insight', 'Spring week / insight'), action: t('Explore', 'Explora'), when: t('Year ', 'Ano ') + (years - 2), duration: t('A few days to 1–2 weeks', 'Alguns dias a 1–2 semanas'), body: t('A short introduction: meet teams, try workshops and discover whether the work interests you. Especially common in finance.', 'Uma breve introdução: conhece equipas, participa em workshops e descobre se a área te interessa. Muito comum em finanças.'), who: t('Often first year of a 3-year degree, or second year of a 4-year degree: roughly two years from graduation when attending. Check the employer’s graduation-date window.', 'Frequentemente no 1.º ano de uma licenciatura de 3 anos, ou no 2.º de um curso de 4 anos: cerca de dois anos até concluir, à data do programa. Confirma as datas de conclusão aceites.') },
    { title: t('Summer internship', 'Estágio de verão'), action: t('Experience', 'Experimenta'), when: t('Summer after year ', 'Verão após o ano ') + (years - 1), duration: t('Typically 2–3 months', 'Geralmente 2–3 meses'), body: t('Longer, hands-on experience with real projects and a team. You build skills, test a career and may be considered for a return offer.', 'Experiência mais longa, com projetos reais e uma equipa. Desenvolves competências, experimentas uma carreira e podes ser considerado para uma oferta futura.'), who: t('Often for penultimate-year students, but some employers accept other years or graduates. A year-long placement is a different format.', 'Muitas vezes para estudantes do penúltimo ano, mas alguns empregadores aceitam outros anos ou graduados. Um placement de um ano é um formato diferente.') },
    { title: t('Graduate programme / job', 'Programa de graduados / emprego'), action: t('Build', 'Constrói'), when: t('After year ', 'Após o ano ') + years, duration: t('Schemes often last 1–3 years', 'Programas muitas vezes de 1–3 anos'), body: t('A paid job with structured training, mentoring and sometimes rotations. A direct-entry graduate job is usually tied to one role instead.', 'Um emprego remunerado com formação estruturada, acompanhamento e, por vezes, rotação entre equipas. Um emprego de entrada direta costuma focar-se numa função.'), who: t('For final-year students applying ahead, or eligible recent graduates. Check the degree, graduation window and right-to-work requirements.', 'Para finalistas que se candidatam antecipadamente ou recém-graduados elegíveis. Confirma o curso, as datas de conclusão e o direito ao trabalho.') },
  ]
  return <section className="tk-pathway tk-section" id="career-path" aria-labelledby="pathway-title">
    <div className="tk-wrap">
      <div className="tk-section-heading"><div><p className="tk-eyebrow">{t('THE BIG PICTURE', 'A VISÃO GERAL')}</p><Heading id="pathway-title">{t('From spring insight to your first job','Do spring insight ao primeiro emprego')}</Heading></div><p>{t('Spring, summer, then your first role. A common route, not a ladder you must follow.', 'Primavera, verão e o primeiro emprego. Um percurso comum, não uma sequência obrigatória.')}</p></div>
      <div className="tk-degree-row"><span>{t('Illustrative undergraduate route', 'Percurso universitário ilustrativo')}</span><div role="group" aria-label={t('Degree length', 'Duração do curso')}>{[3,4].map(n=><button key={n} aria-pressed={years===n} onClick={()=>setYears(n)}>{n}{t('-year degree', ' anos de curso')}</button>)}</div></div>
      <ol className="tk-path-steps">{cards.map((card,i)=><li key={i} className={'tk-path-step tk-path-step-'+i}>
        <div className="tk-path-station"><span>0{i+1}</span><strong>{card.action}</strong><span aria-hidden="true">↗</span></div>
        <div className="tk-path-icon" aria-hidden="true"><svg viewBox="0 0 100 70" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{i===0?<><path d="M14 14h24q12 0 12 8v38q-6-7-14-7H14V14Zm72 0H62q-12 0-12 8v38q6-7 14-7h22V14Z"/><path d="M23 25h15m-15 9h15m24-9h15m-15 9h15"/><path className="tk-path-accent" d="m66 47 6 5 13-16"/></>:i===1?<><rect x="13" y="21" width="74" height="40" rx="4"/><path d="M36 21v-9h28v9M13 34q37 20 74 0"/><rect x="43" y="36" width="14" height="10" rx="2"/><path className="tk-path-accent" d="m70 9 6-6m5 12h9"/></>:<><path d="M12 61h78M22 61V16h36v45M58 29h22v32M31 25h5m9 0h5m-19 10h5m9 0h5m-19 10h5m9 0h5m17-8h5m-5 10h5"/><path className="tk-path-accent" d="M65 17 78 4m-13 0h13v13"/></>}</svg></div>
        <p className="tk-path-year" aria-live="polite">{card.when}</p><h3>{card.title}</h3><p className="tk-path-duration">{card.duration}</p><p>{card.body}</p><details><summary>{t('Who is it usually for?', 'A quem se destina?')} <span aria-hidden="true">+</span></summary><p>{card.who}</p></details>
      </li>)}</ol>
      <div className="tk-path-bottom"><p><strong>{t('Apply before you get there.', 'Candidata-te antes de lá chegares.')}</strong> {t('Many large employers recruit in the autumn before the programme starts. Dates vary: do not wait until spring or summer to look.', 'Muitos grandes empregadores recrutam no outono anterior ao início do programa. Os prazos variam: não esperes pela primavera ou pelo verão para procurar.')}</p><p><strong>{t('Missed a step? You still have options.', 'Saltaste uma etapa? Há outros caminhos.')}</strong> {t('You can apply directly for summer internships, graduate schemes or entry-level jobs. An insight or internship never guarantees the next offer.', 'Podes candidatar-te diretamente a estágios de verão, programas de graduados ou empregos de entrada. Um insight ou estágio nunca garante a oferta seguinte.')}</p></div>
      <details className="tk-path-sources"><summary>{t('Sources & eligibility notes', 'Fontes e notas de elegibilidade')}</summary><p>{t('This is a guide, not a universal eligibility rule. Check each employer’s dates, degree requirements and programme length.', 'Este é um guia, não uma regra universal de elegibilidade. Confirma datas, requisitos académicos e duração com cada empregador.')}</p><div><a href="https://jobs.citi.com/early-career-programs-pre-internships" target="_blank" rel="noopener noreferrer">Citi · {t('spring eligibility', 'elegibilidade spring')} ↗</a><a href="https://www.prospects.ac.uk/jobs-and-work-experience/work-experience-and-internships/internships/" target="_blank" rel="noopener noreferrer">Prospects · {t('internships', 'estágios')} ↗</a><a href="https://www.prospects.ac.uk/careers-advice/getting-a-job/graduate-schemes/" target="_blank" rel="noopener noreferrer">Prospects · {t('graduate schemes', 'programas de graduados')} ↗</a></div></details>
    </div>
  </section>
}
