import { useLang } from '../../context/LanguageContext'
import { asset } from '../../utils/asset'

const platforms = [
 { name:'Trackr', logo:'trackr.png', tag:['Application trackers','Trackers de candidaturas'], desc:['Explore internship and graduate trackers across sectors. Some tools require an account or paid plan.','Explora trackers de estágios e programas de graduados em vários setores. Algumas ferramentas exigem conta ou plano pago.'], url:'https://the-trackr.com/', theme:'green' },
 { name:'Handshake', logo:'handshake.svg', tag:['Student career network','Rede de carreiras para estudantes'], desc:['Find early-career opportunities and events. Check whether your university uses Handshake; access varies.','Encontra oportunidades e eventos de início de carreira. Confirma se a tua universidade usa Handshake; o acesso varia.'], url:'https://joinhandshake.com/students/', theme:'green' },
 { name:'Indeed', logo:'indeed.png', tag:['Broad UK search','Pesquisa geral UK'], desc:['Search internships and entry-level roles by title and city. Confirm the original vacancy with the employer.','Pesquisa estágios e funções de entrada por título e cidade. Confirma a vaga original com o empregador.'], url:'https://uk.indeed.com/UK-Internship-jobs', theme:'blue' },
 { name:'10,000 Black Interns', logo:'interns.png', tag:['Programme · eligibility applies','Programa · critérios próprios'], desc:['Paid internships across sectors for eligible Black students and graduates. Check the current education and right-to-work criteria before applying.','Estágios remunerados em vários setores para estudantes e graduados negros elegíveis. Confirma os critérios académicos e de direito ao trabalho antes de te candidatares.'], url:'https://10000internsfoundation.com/students-graduates/10000-black-interns/', theme:'yellow' },
 { name:'LinkedIn Jobs', logo:'linkedin.ico', tag:['Jobs + employer research','Emprego + pesquisa de empresas'], desc:['Combine UK internship searches with company and team research. Try different role names and locations.','Combina pesquisas de estágios UK com informação sobre empresas e equipas. Experimenta funções e localizações diferentes.'], url:'https://www.linkedin.com/jobs/search/?keywords=internship&location=United%20Kingdom', theme:'blue' },
 { name:'Bright Network', logo:'bright.png', tag:['Insights, internships & events','Insights, estágios e eventos'], desc:['Explore spring insights, summer internships and graduate opportunities across sectors.','Explora spring insights, estágios de verão e oportunidades para graduados em vários setores.'], url:'https://www.brightnetwork.co.uk/work-experience/', theme:'yellow' },
 { name:'Gradcracker', logo:'gradcracker.png', tag:['Engineering, technology & STEM','Engenharia, tecnologia e STEM'], desc:['Find placements, internships and graduate jobs by discipline, including engineering and technical routes.','Encontra placements, estágios e empregos para graduados por disciplina, incluindo percursos de engenharia e tecnologia.'], url:'https://www.gradcracker.com/', theme:'green' },
] as const

export default function DiscoveryPlatforms() {
 const {lang}=useLang()
 const l=lang==='pt'?1:0
 const t=(en:string,pt:string)=>l?pt:en
 return <section className="tk-discovery tk-section" id="discovery-platforms" aria-labelledby="platforms-title"><div className="tk-wrap">
  <div className="tk-section-heading"><div><p className="tk-eyebrow">{t('KEEP EXPLORING','CONTINUA A EXPLORAR')}</p><h2 id="platforms-title">{t('Other opportunity platforms','Outras plataformas de oportunidades')}</h2></div><p>{t('Our tracker is a starting point. Explore these independent platforms and programmes for more opportunities.','O nosso tracker é um ponto de partida. Explora estas plataformas e programas independentes para encontrar mais oportunidades.')}</p></div>
  <div className="tk-platform-grid tk-platform-grid-brands">{platforms.map(p=><a className={'tk-platform tk-platform-'+p.theme} href={p.url} key={p.name} target="_blank" rel="noopener noreferrer"><div className="tk-platform-top"><span className="tk-platform-brand"><img src={asset('/assets/platforms/'+p.logo)} alt="" width="48" height="48" loading="lazy"/></span><svg aria-hidden="true" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M5 19 19 5M5 5h14v14"/></svg></div><h3>{p.name}</h3><p className="tk-platform-category">{p.tag[l]}</p><p>{p.desc[l]}</p><span className="tk-platform-link">{p.name==='10,000 Black Interns'?t('Explore programme & eligibility','Ver programa e elegibilidade'):t('Explore platform','Explorar plataforma')} ↗</span></a>)}</div>
  <div className="tk-platform-tip"><span aria-hidden="true">↗</span><p><strong>{t('Search beyond London.','Pesquisa para além de Londres.')}</strong> {t('Try Bristol, Manchester or another city, and keywords such as “spring insight”, “engineering placement” or “property internship”. Check employer websites and your university careers portal too.','Experimenta Bristol, Manchester ou outra cidade e termos como “spring insight”, “engineering placement” ou “property internship”. Consulta também os empregadores e o portal de carreiras da tua universidade.')}</p></div>
  <p className="tk-platform-note">{t('Logos identify independent services, not partnerships or endorsement. Accounts may be required. Each platform or programme sets its own eligibility and access rules.','Os logótipos identificam serviços independentes, não parcerias nem apoio institucional. Pode ser necessário criar conta. Cada plataforma ou programa tem critérios próprios de elegibilidade e acesso.')}</p>
 </div></section>
}
