import {Link} from 'react-router-dom'
import {useState} from 'react'
import {motion, useReducedMotion} from 'motion/react'
import {TipIcon} from './CareerIllustrations'
import {useLang} from '../../context/LanguageContext'
import '../../styles/career-additions.css'

export default function RecruitmentCalendar(){
 const {lang}=useLang(),t=(en:string,pt:string)=>lang==='pt'?pt:en
 const [tip,setTip]=useState(0)
 const [programme,setProgramme]=useState(0)
 const reduce=useReducedMotion()
 const rows=[
  [t('Spring weeks / insights','Spring weeks / insights'),t('From September','A partir de setembro'),t('Check through autumn and winter; dates vary by employer.','Acompanha durante o outono e inverno; as datas variam por empresa.'),t('Usually around Easter','Geralmente na Páscoa'),t('Often first year of a three-year degree, or second year of a four-year degree. Check each programme.','Frequentemente no 1.º ano de uma licenciatura de três anos ou no 2.º de um curso de quatro anos. Confirma cada programa.')],
  [t('Summer internships','Estágios de verão'),t('Previous summer / autumn','Verão / outono anteriores'),t('Some large employers open as early as July. Other employers advertise later, including in spring.','Algumas grandes empresas abrem logo em julho. Outras anunciam mais tarde, incluindo na primavera.'),t('Following summer','Verão seguinte'),t('Often the penultimate year. Eligibility and internship length depend on the employer.','Frequentemente no penúltimo ano. A elegibilidade e a duração dependem da empresa.')],
  [t('Graduate schemes','Programas de graduados'),t('September–November','Setembro–novembro'),t('A common recruitment period, not a universal deadline. Some schemes open earlier or close later.','Um período frequente de recrutamento, não um prazo universal. Alguns programas abrem antes ou fecham depois.'),t('Often the following autumn','Muitas vezes no outono seguinte'),t('Final-year students and graduates. Structured training alongside a job.','Estudantes finalistas e graduados. Formação estruturada em conjunto com uma função profissional.')],
  [t('Direct-entry graduate jobs','Empregos de entrada para graduados'),t('Throughout the year','Ao longo do ano'),t('Apply when a suitable vacancy appears and you can meet its start date.','Candidata-te quando surgir uma vaga adequada e conseguires cumprir a data de entrada.'),t('As agreed with the employer','Conforme acordado com a empresa'),t('A specific role rather than an annual training programme.','Uma função específica, em vez de um programa anual de formação.')]
 ]
 const tips=[
  [t('Speak to alumni and professionals','Fala com antigos alunos e profissionais'),t('Ask about their work and recruitment experience. If they know your work and the company accepts referrals, ask whether a referral would be appropriate. It does not replace the application or guarantee an interview.','Pergunta sobre o trabalho e a experiência de recrutamento. Se conhecerem o teu trabalho e a empresa aceitar recomendações internas, pergunta se faria sentido uma referral. Não substitui a candidatura nem garante entrevista.')],
  [t('Send targeted emails','Envia emails direcionados'),t('Contact a relevant person with a short introduction, a specific reason for writing and one clear question. For a speculative application, explain what you could contribute and attach a tailored CV. Avoid mass emails.','Contacta uma pessoa relevante com uma apresentação breve, um motivo específico e uma pergunta clara. Numa candidatura espontânea, explica o que podes acrescentar e anexa um CV adaptado. Evita emails em massa.')],
  [t('Attend employer insight events','Participa em eventos de empresas'),t('Look for insight days, webinars and university careers fairs. Prepare questions about teams and eligibility, note what you learn and follow up with people you meet. Events can have their own application deadlines.','Procura insight days, webinars e feiras de emprego universitárias. Prepara perguntas sobre equipas e elegibilidade, regista o que aprendeste e mantém contacto com quem conheceste. Os eventos também podem ter prazos de inscrição.')],
  [t('Prepare before applications open','Prepara-te antes da abertura'),t('Shortlist roles, set alerts and prepare your CV and examples for interviews. Where applications are reviewed on a rolling basis, apply when ready rather than waiting for the closing date.','Seleciona funções, ativa alertas e prepara o CV e exemplos para entrevistas. Quando as candidaturas são avaliadas à medida que chegam, candidata-te assim que estiveres preparado, sem esperar pelo último dia.')]
 ]
 return <section className="tk-section recruitment-calendar" id="recruitment-calendar" aria-labelledby="calendar-heading"><div className="tk-wrap">
  <p className="tk-eyebrow">{t('PLANNING YOUR APPLICATIONS','PLANEAR AS CANDIDATURAS')}</p>
  <div className="calendar-intro"><h2 id="calendar-heading">{t('When should you apply?','Quando deves candidatar-te?')}</h2><p>{t('Many UK employers recruit months before the start date. Use this calendar to plan your search, then check the dates and eligibility on each employer’s website.','Muitas empresas no Reino Unido recrutam meses antes da data de entrada. Usa este calendário para planear a pesquisa e confirma as datas e os requisitos no website de cada empresa.')}</p></div>
  <div className="calendar-desk"><div className="calendar-rings" aria-hidden="true"><i/><i/><i/></div><div className="calendar-visual-heading"><div><h3>{t('Who should apply, and when','Quem se deve candidatar, e quando')}</h3><p>{t('Choose a programme to see its usual application window and eligibility. Confirm the details with each employer.','Escolhe um programa para ver o período habitual de candidatura e os requisitos. Confirma os detalhes com cada empresa.')}</p></div></div>
  <div className="calendar-programmes" role="group" aria-label={t('Choose a programme','Escolhe um programa')}>{rows.map(([name],i)=><button key={i} aria-pressed={programme===i} aria-controls="calendar-programme" onClick={()=>setProgramme(i)}><span>0{i+1}</span>{name}</button>)}</div>
  <div className="calendar-page-stage" aria-live="polite" aria-atomic="true"><motion.article id="calendar-programme" key={programme} className="calendar-programme" initial={reduce?false:{opacity:0,rotateX:-12,y:12}} animate={{opacity:1,rotateX:0,y:0}} transition={{duration:reduce?0:.4,ease:[.22,1,.36,1]}}>
   <header><span className="calendar-page-number">0{programme+1} / 04</span><h4>{rows[programme][0]}</h4></header>
   <div className="calendar-programme-panels">
    <div className="calendar-apply-panel"><p className="calendar-panel-label">{t('WHEN TO APPLY','QUANDO CANDIDATAR-TE')}</p><h5>{rows[programme][1]}</h5><p>{rows[programme][2]}</p></div>
    <div className="calendar-eligibility-panel"><p className="calendar-panel-label">{t('WHEN IT HAPPENS & WHO IT’S FOR','QUANDO DECORRE E A QUEM SE DESTINA')}</p><h5>{rows[programme][3]}</h5><p>{rows[programme][4]}</p></div>
   </div>
  </motion.article></div>
  <nav className="calendar-page-controls" aria-label={t('Calendar navigation','Navegação do calendário')}><button disabled={programme===0} onClick={()=>setProgramme(i=>i-1)} aria-label={t('Previous programme','Programa anterior')}>← <span>{t('Previous','Anterior')}</span></button><span>{programme+1} / {rows.length}</span><button onClick={()=>setProgramme(i=>(i+1)%rows.length)}>{programme===3?t('Back to first','Voltar ao início'):t('Next','Seguinte')} →</button></nav>
  <p className="calendar-timing-note">{t('Typical UK recruitment cycle. Indicative timing, not live deadlines.','Ciclo habitual de recrutamento no Reino Unido. Períodos indicativos, não prazos de vagas atuais.')}</p>
  </div>
  <div className="calendar-foot"><p>{t('These patterns are most useful for structured early-career programmes. Smaller employers and other sectors may recruit at different times. You do not need a spring week to apply for a summer internship.','Estes padrões são sobretudo úteis para programas estruturados de início de carreira. Empresas mais pequenas e outros setores podem recrutar noutras alturas. Não precisas de ter feito uma spring week para te candidatares a um estágio de verão.')}</p><Link to="/tracker">{t('See opportunities','Ver oportunidades')} ↗</Link></div>
  <details className="calendar-sources"><summary>{t('Sources and timing notes','Fontes e notas sobre os períodos')}</summary><p>{t('Guidance checked on 6 October 2026. Spring and early summer-internship timing draws on Oxford’s banking guidance; it is not a timetable for every sector.','Orientações consultadas a 6 de outubro de 2026. Os períodos de spring weeks e de abertura antecipada de estágios baseiam-se nas orientações de Oxford para a banca; não são um calendário para todos os setores.')}</p><ul><li><a href="https://www.careers.ox.ac.uk/banking-investment" target="_blank" rel="noreferrer">Oxford Careers: {t('spring weeks, internships and employer events','spring weeks, estágios e eventos de empresas')} ↗</a></li><li><a href="https://nationalcareers.service.gov.uk/careers-advice/how-to-find-graduate-schemes" target="_blank" rel="noreferrer">National Careers Service: {t('graduate schemes','programas de graduados')} ↗</a></li><li><a href="https://info.lse.ac.uk/current-students/careers/information-and-resources/looking-for-work/graduate-job-market" target="_blank" rel="noreferrer">LSE Careers: {t('graduate recruitment','recrutamento de graduados')} ↗</a></li><li><a href="https://www.careers.ox.ac.uk/making-speculative-approaches" target="_blank" rel="noreferrer">Oxford Careers: {t('speculative applications','candidaturas espontâneas')} ↗</a></li></ul></details>
  <div className="calendar-tips"><h3>{t('What to do alongside your applications','O que fazer além das candidaturas')}</h3><div className="career-tip-stepper">
   <div className="career-tip-tabs" role="group" aria-label={t('Application preparation tips','Conselhos de preparação')}>
    {tips.map(([title],i)=><button key={i} aria-pressed={tip===i} onClick={()=>setTip(i)}><TipIcon index={i}/><span className="career-tip-label">{title}</span><span aria-hidden="true">↗</span></button>)}
   </div>
   <div className="career-tip-panel"><div aria-live="polite" aria-atomic="true"><motion.article key={tip} initial={reduce?false:{opacity:0,x:16}} animate={{opacity:1,x:0}} transition={{duration:.25}}><div className="career-tip-panel-heading"><TipIcon index={tip} animated/><span>0{tip+1} / 04</span></div><h4>{tips[tip][0]}</h4><p>{tips[tip][1]}</p></motion.article></div>
   <nav aria-label={t('Tip navigation','Navegação dos conselhos')}><button disabled={tip===0} onClick={()=>setTip(i=>i-1)} aria-label={t('Previous tip','Conselho anterior')}>←</button><button onClick={()=>setTip(i=>(i+1)%tips.length)}>{tip===3?t('Back to first','Voltar ao primeiro'):t('Next tip','Próximo conselho')} →</button></nav></div>
  </div></div>
 </div></section>
}
