import {useState} from 'react'
import {Link} from 'react-router-dom'
import {useLang} from '../context/LanguageContext'
import {asset} from '../utils/asset'
import {employers} from '../content/tracker-employers'
import UkFlag from '../components/tracker/UkFlag'
export default function HomePage(){
 const {lang}=useLang(),l=lang==='pt'?1:0,t=(en:string,pt:string)=>l?pt:en
 const [paused,setPaused]=useState(false)
 const destinations=[
 ['/tracker',t('Opportunities tracker','Tracker de oportunidades'),t('Search by area, programme and UK city. Expand employers to compare their roles.','Pesquisa por área, programa e cidade britânica. Expande cada empregador para comparar as suas oportunidades.'),'01'],
 ['/programmes',t('Find your programme','Encontra o teu programa'),t('Understand spring insights, summer internships and graduate routes.','Compreende os spring insights, estágios de verão e percursos para graduados.'),'02'],
 ['/process',t('Recruitment, step by step','O recrutamento, passo a passo'),t('Online assessments, recorded interviews, live interviews and assessment centres.','Avaliações online, entrevistas gravadas, entrevistas ao vivo e assessment centres.'),'03'],
 ['/cv-101',t('CV 101','CV 101'),t('Read the 244 Club guide. Explore all seven pages in the reader or download the PDF.','Lê o guia do 244 Club. Explora as sete páginas no leitor ou descarrega o PDF.'),'04'],
 ]
 return <div className="tk-page careers-home">
     <section className="tk-hero" aria-labelledby="tracker-heading"><div className="tk-wrap tk-hero-grid">
      <div className="tk-hero-copy"><p className="tk-eyebrow"><UkFlag/>244 CAREERS / {t('PROFESSIONAL DEVELOPMENT', 'DESENVOLVIMENTO PROFISSIONAL')}</p><h1 id="tracker-heading">{t('Opportunities tracker', 'Tracker de oportunidades')}<br/><em>{t('& career guide.', '& guia de carreira.')}</em></h1><p>{t('Built by 244 Club for our members, students, young professionals and anyone exploring UK careers. Find opportunities across sectors, understand how recruitment works and prepare your next move.', 'Criado pelo 244 Club para os nossos membros, estudantes, jovens profissionais e todos os que exploram carreiras no Reino Unido. Encontra oportunidades em vários setores, compreende o recrutamento e prepara o próximo passo.')}</p><div className="tk-actions"><a className="tk-btn tk-btn-lime" href="/tracker">{t('Explore opportunities', 'Explorar oportunidades')} ↗</a><a className="tk-btn tk-btn-ghost" href="/programmes">{t('Find your starting point', 'Encontra o teu ponto de partida')} ↓</a></div><p className="tk-hero-footnote">{t('Open to everyone. No membership or account needed.', 'Aberto a todos. Sem necessidade de ser membro ou criar conta.')}</p></div>
      <div className="tk-hero-board" aria-label={t('Collection overview', 'Visão da coleção')}><div className="tk-board-top"><span>244 / {t('OPPORTUNITY INDEX', 'ÍNDICE DE OPORTUNIDADES')}</span><span>2027</span></div><div className="tk-board-overview"><strong>50+<span aria-hidden="true">↗</span></strong><p>{t('opportunities across', 'oportunidades em')}</p><ul>{[t('Finance','Finanças'),t('Real estate','Imobiliário'),t('Consulting','Consultoria'),t('Technology','Tecnologia'),t('Engineering','Engenharia')].map(area=><li key={area}>{area}</li>)}</ul></div><div className="tk-board-path"><span>{t('DISCOVER', 'DESCOBRE')}</span><i/><span>{t('PREPARE', 'PREPARA')}</span><i/><span>{t('APPLY', 'CANDIDATA-TE')}</span></div><div className="tk-board-bottom"><span>{t('UK CAREER OPPORTUNITIES', 'OPORTUNIDADES NO REINO UNIDO')}</span><span>↗</span></div></div>
    </div></section>


     <section className={`tk-employers ${paused?'is-paused':''}`} aria-label={t('Some employers in this collection', 'Alguns empregadores desta coleção')}><div className="tk-wrap tk-brand-heading"><p>{t('Some of the UK’s Best Employers', 'Alguns dos Melhores Empregadores do Reino Unido')}</p><button className="tk-motion-toggle" onClick={()=>setPaused(p=>!p)} aria-pressed={paused} aria-label={paused?t('Resume employer logos','Retomar logótipos'):t('Pause employer logos','Pausar logótipos')}><svg width="18" height="18" viewBox="0 0 20 20" aria-hidden="true" fill="currentColor">{paused?<path d="m6 3 11 7-11 7z"/>:<path d="M5 3h3v14H5zm7 0h3v14h-3z"/>}</svg></button></div><div className="tk-marquee"><div className="tk-marquee-track">{[0,1].map(copy=><div className="tk-logo-set" key={copy} aria-hidden={copy===1?true:undefined}>{employers.map(e=><a className={'tk-logo '+(e.icon?'tk-logo-with-name':'')} href={e.url} key={e.name} target="_blank" rel="noopener noreferrer" tabIndex={copy===1?-1:0} aria-label={copy===0?e.name:undefined}><img src={asset('/assets/employers/'+e.file)} alt={e.icon?'':e.name} width={e.icon?36:160} height={e.icon?36:52}/>{e.icon&&<span>{e.name}</span>}</a>)}</div>)}</div></div><p className="tk-brand-disclaimer">{t('An editorial selection, not a ranking. Click a logo to visit the employer. No affiliation or partnership implied.', 'Uma seleção editorial, não um ranking. Clica num logótipo para visitar a empresa. Sem afiliação ou parceria.')}</p></section>


 <section className="careers-destinations tk-section"><div className="tk-wrap"><p className="tk-eyebrow">244 CAREERS</p><h2>{t('What are you looking for?','O que procuras?')}</h2><div className="careers-destination-grid">{destinations.map(([to,title,desc,num])=><Link className="careers-destination" key={to} to={to}><span>{num} <b aria-hidden="true">↗</b></span><h3>{title}</h3><p>{desc}</p></Link>)}</div><Link className="careers-resource-link" to="/resources">{t('Explore preparation resources, useful websites and FAQs','Explora recursos de preparação, websites úteis e perguntas frequentes')} ↗</Link></div></section>
     <section className="tk-why tk-section"><div className="tk-wrap tk-why-grid"><div><p className="tk-eyebrow">{t('WHY WE BUILT THIS', 'PORQUE CRIÁMOS ESTA PÁGINA')}</p><h2>{t('UK career information, in one place.', 'O panorama de oportunidades no Reino Unido, num só lugar.')}</h2></div><div><p>{t('We created this page to bring information about the range of opportunities in the United Kingdom together, for university students and beyond. Here you can explore career options, understand recruitment processes and find preparation resources.', 'Criámos esta página para centralizar a informação sobre o panorama de oportunidades no Reino Unido, para estudantes universitários e não só. Aqui podes explorar percursos profissionais, compreender os processos de recrutamento e encontrar recursos de preparação.')}</p><p>{t('The tracker brings together opportunities in finance, consulting, real estate, technology and engineering, among other fields. Filter by area to find the roles that interest you. The guide explains programme types and recruitment stages so you can decide where to start.', 'O tracker reúne oportunidades em finanças, consultoria, imobiliário, tecnologia e engenharia, entre outras áreas. Filtra por área para encontrares as funções que te interessam. O guia explica os tipos de programa e as etapas de recrutamento para te ajudar a decidir por onde começar.')}</p></div></div></section>

 </div>
}
