export const site='https://careers.244club.com'
export const pages:Record<string,{title:[string,string];description:[string,string]}>={
 '/':{title:['244 Careers | UK Opportunities & Career Guide','244 Careers | Oportunidades e guia de carreira no Reino Unido'],description:['Find UK internships across sectors and prepare with 244 Club’s programme guide, recruitment explainers and CV 101.','Encontra estágios no Reino Unido em vários setores e prepara-te com os guias de programas, recrutamento e CV 101 do 244 Club.']},
 '/tracker':{title:['UK Opportunities Tracker | 244 Careers','Tracker de oportunidades no Reino Unido | 244 Careers'],description:['Browse spring insights and internships by area, city and employer. Compare programmes and follow employer application links.','Explora spring insights e estágios por área, cidade e empregador. Compara programas e consulta as candidaturas nas páginas das empresas.']},
 '/programmes':{title:['Spring, Summer & Graduate Programmes | 244 Careers','Spring, verão e programas de graduados | 244 Careers'],description:['Understand programme types, degree-year eligibility and common routes into UK careers.','Compreende os tipos de programa, os anos de curso elegíveis e os percursos de carreira no Reino Unido.']},
 '/process':{title:['Recruitment Process: OA, HireVue, Interviews & AC | 244 Careers','Processo de recrutamento: OA, HireVue, entrevistas e AC | 244 Careers'],description:['Learn what to expect from online assessments, recorded interviews, live interviews and assessment centres, with preparation resources.','Descobre como funcionam as avaliações online, entrevistas gravadas, entrevistas ao vivo e assessment centres, com recursos de preparação.']},
 '/cv-101':{title:['CV 101 by Yusseni Furtado | 244 Careers','CV 101 de Yusseni Furtado | 244 Careers'],description:['Preview and download the seven-page CV 101 guide by Yusseni Furtado for 244 Club.','Pré-visualiza e descarrega o guia CV 101 de sete páginas de Yusseni Furtado para o 244 Club.']},
 '/resources':{title:['Preparation Resources & FAQ | 244 Careers','Recursos de preparação e FAQ | 244 Careers'],description:['Find practical CV, assessment and interview resources, with answers to common UK career questions.','Encontra recursos práticos para CV, avaliações e entrevistas, com respostas a perguntas frequentes sobre carreiras no Reino Unido.']}
}
