export const stages = [
  { code: 'OA', title: ['Online assessments', 'Testes online'], summary: ['Reasoning, judgement and sometimes coding. Get familiar with the format before the timer starts.', 'Raciocínio, julgamento e, por vezes, programação. Conhece o formato antes de começar o cronómetro.'], detail: ['You may see numerical, verbal or logical reasoning, workplace scenarios (SJTs), game-based exercises or coding tasks. Use the employer’s own practice questions first.', 'Podes encontrar raciocínio numérico, verbal ou lógico, cenários profissionais (SJT), exercícios interativos ou programação. Começa pelos exemplos do próprio empregador.'], tips: [['Practise percentages, ratios and charts.', 'Read the instructions; use only permitted tools.', 'Request accessibility adjustments in advance.'], ['Pratica percentagens, rácios e gráficos.', 'Lê as instruções e usa apenas ferramentas permitidas.', 'Pede adaptações de acessibilidade com antecedência.']], avoid: ['Don’t rush the instructions or get help during a live assessment.', 'Não saltes as instruções nem peças ajuda durante um teste real.'], resource: 'https://www.shl.com/shldirect/en/practice-tests/', resourceName: 'SHL practice tests' },
  { code: 'HV', title: ['Recorded video interview', 'Entrevista em vídeo gravado'], summary: ['A question, a little thinking time, then your answer. Make it clear, specific and yours.', 'Uma pergunta, algum tempo para pensar e a tua resposta. Sê claro, específico e autêntico.'], detail: ['HireVue is a platform, not a universal interview stage. Other platforms exist. Prepare real examples using STAR: Situation, Task, Action, Result.', 'HireVue é uma plataforma, não uma etapa universal. Existem outras. Prepara exemplos reais com STAR: Situação, Tarefa, Ação e Resultado.'], tips: [['Test your audio, camera and internet.', 'Practise concise answers aloud.', 'Use the practice question before recording.'], ['Testa o som, a câmara e a internet.', 'Pratica respostas concisas em voz alta.', 'Usa a pergunta de treino antes de gravar.']], avoid: ['Avoid reading a memorised script. Answer the question you were actually asked.', 'Evita ler um guião decorado. Responde à pergunta que te fizeram.'], resource: 'https://www.hirevue.com/candidates/interview-tips', resourceName: 'HireVue candidate tips' },
  { code: 'INT', title: ['Live interviews', 'Entrevistas ao vivo'], summary: ['Show how you think, what you have done and why this opportunity makes sense for you.', 'Mostra como pensas, o que já fizeste e porque esta oportunidade faz sentido para ti.'], detail: ['Expect motivation and competency questions, with technical questions or cases depending on the role. Banking can involve accounting and markets; consulting can include business cases.', 'Espera perguntas de motivação e competências, com questões técnicas ou casos conforme a função. Banca pode incluir contabilidade e mercados; consultoria pode incluir casos de negócio.'], tips: [['Prepare a short introduction and specific examples.', 'Research the team, employer and recent developments.', 'Practise aloud and bring thoughtful questions.'], ['Prepara uma apresentação breve e exemplos concretos.', 'Pesquisa a equipa, o empregador e notícias recentes.', 'Pratica em voz alta e prepara boas perguntas.']], avoid: ['Don’t bluff a technical answer. Explain your reasoning and what you do know.', 'Não inventes uma resposta técnica. Explica o teu raciocínio e o que sabes.'], resource: 'https://careers.bcg.com/global/en/case-interview-preparation', resourceName: 'BCG case preparation' },
  { code: 'AC', title: ['Assessment centre', 'Centro de avaliação'], summary: ['Several exercises, one opportunity to show how you work with people and information.', 'Vários exercícios, uma oportunidade de mostrar como trabalhas com pessoas e informação.'], detail: ['An assessment centre may be online or in person, with group tasks, presentations, written analysis or interviews. Formats vary by employer; there is no single standard route.', 'Pode decorrer online ou presencialmente, com tarefas de grupo, apresentações, análise escrita ou entrevistas. O formato depende do empregador; não existe um percurso único.'], tips: [['Contribute early and include quieter voices.', 'Watch the time and prioritise the key facts.', 'Make a recommendation and explain why.'], ['Participa cedo e inclui quem fala menos.', 'Gere o tempo e prioriza os factos essenciais.', 'Apresenta uma recomendação e explica porquê.']], avoid: ['Don’t dominate the group or treat other candidates as opponents.', 'Não domines o grupo nem trates os outros candidatos como adversários.'], resource: 'https://www.ucl.ac.uk/study/careers/ucl-careers/preparing-your-application/assessment-centres', resourceName: 'UCL assessment centres' },
] as const

export const resources = [
  { stage: 'CV', provider: 'Prospects', title: ['Write a clearer CV', 'Escreve um CV mais claro'], desc: ['Structure, evidence and formatting for a UK application.', 'Estrutura, provas e formatação para candidaturas no Reino Unido.'], access: ['Free guide', 'Guia gratuito'], url: 'https://www.prospects.ac.uk/careers-advice/cvs-and-cover-letters/how-to-write-a-cv/' },
  { stage: 'CV', provider: 'Prospects', title: ['Cover letters that add something', 'Cartas de apresentação com valor'], desc: ['Connect your experience to the role. Follow the employer’s instructions.', 'Liga a tua experiência à função. Segue as instruções do empregador.'], access: ['Free guide', 'Guia gratuito'], url: 'https://www.prospects.ac.uk/careers-advice/cvs-and-cover-letters/cover-letters/' },
  { stage: 'OA', provider: 'SHL', title: ['Practise the assessment format', 'Pratica o formato dos testes'], desc: ['Numerical, verbal and other example assessments. Registration may apply.', 'Exemplos de testes numéricos, verbais e outros. Pode exigir registo.'], access: ['Free examples', 'Exemplos gratuitos'], url: 'https://www.shl.com/shldirect/en/practice-tests/' },
  { stage: 'OA', provider: 'AssessmentDay · YouTube', title: ['Numerical reasoning, explained', 'Raciocínio numérico, explicado'], desc: ['A video walkthrough. Supplement it with current employer practice tests.', 'Um vídeo de explicação. Complementa com testes atuais do empregador.'], access: ['Free video · 2019', 'Vídeo gratuito · 2019'], url: 'https://www.youtube.com/watch?v=p39ai9Ho_uw' },
  { stage: 'HV', provider: 'HireVue', title: ['Feel ready for the camera', 'Prepara-te para a câmara'], desc: ['Practical guidance from the interview platform itself.', 'Orientações práticas da própria plataforma de entrevistas.'], access: ['Free guide', 'Guia gratuito'], url: 'https://www.hirevue.com/candidates/interview-tips' },
  { stage: 'INT', provider: 'Villanova University', title: ['Finance interview fundamentals', 'Fundamentos da entrevista financeira'], desc: ['Technical finance preparation. Some terminology is US-oriented.', 'Preparação técnica em finanças. Parte da terminologia é americana.'], access: ['Free guide', 'Guia gratuito'], url: 'https://connections.villanova.edu/resources/finance-technical-interview-guide/' },
  { stage: 'INT', provider: 'BCG', title: ['Think through a case', 'Raciocina sobre um caso'], desc: ['Official consulting case practice. Other firms may use different formats.', 'Prática oficial de casos de consultoria. Outras empresas podem usar formatos diferentes.'], access: ['Free practice', 'Prática gratuita'], url: 'https://careers.bcg.com/global/en/case-interview-preparation' },
  { stage: 'INT', provider: 'Management Consulted · YouTube', title: ['Watch a mock case interview', 'Vê uma simulação de entrevista'], desc: ['A full case example. The provider also promotes paid coaching.', 'Um exemplo completo. O fornecedor também promove acompanhamento pago.'], access: ['Free video · 2021', 'Vídeo gratuito · 2021'], url: 'https://www.youtube.com/watch?v=EyrjbA6KDHM' },
  { stage: 'OA', provider: 'HackerRank', title: ['Build coding confidence', 'Ganha confiança a programar'], desc: ['Interview preparation exercises. Account required; some features are paid.', 'Exercícios para entrevistas. Exige conta; algumas funcionalidades são pagas.'], access: ['Free tier', 'Plano gratuito'], url: 'https://www.hackerrank.com/interview-preparation-kit' },
  { stage: 'AC', provider: 'UCL Careers', title: ['Know the assessment centre', 'Conhece o centro de avaliação'], desc: ['Understand typical exercises. Some linked services are for UCL students.', 'Conhece os exercícios habituais. Alguns serviços ligados são exclusivos da UCL.'], access: ['Free guide', 'Guia gratuito'], url: 'https://www.ucl.ac.uk/study/careers/ucl-careers/preparing-your-application/assessment-centres' },
  { stage: 'INT', provider: 'Bright Network', title: ['Build commercial awareness', 'Desenvolve visão de negócio'], desc: ['Understand how businesses work and respond to change.', 'Compreende como as empresas funcionam e respondem à mudança.'], access: ['Free guide', 'Guia gratuito'], url: 'https://www.brightnetwork.co.uk/graduate-career-advice/what-is-commercial-awareness/show-commercial-awareness/' },
  { stage: 'Eligibility', provider: 'UKCISA', title: ['Working as an international student', 'Trabalhar como estudante internacional'], desc: ['General guidance. Confirm your own conditions with your university.', 'Orientações gerais. Confirma as tuas condições com a universidade.'], access: ['Free guidance', 'Orientação gratuita'], url: 'https://www.ukcisa.org.uk/student-advice/working/student-work/' },
] as const

export const faqs = [
  { q: ['Who is this page for?', 'A quem se destina esta página?'], a: ['244 Club members, students, young professionals and anyone exploring careers in the UK. Membership is not required. Browse opportunities by area, from consulting and technology to finance, real estate and engineering, then use the pathway and recruitment guides to prepare.', 'A membros do 244 Club, estudantes, jovens profissionais e todos os que exploram carreiras no Reino Unido. Não é necessário ser membro. Explora oportunidades por área, da consultoria e tecnologia às finanças, imobiliário e engenharia, e usa os guias para te preparares.'] },
  { q: ['Are all these programmes open?', 'Todos estes programas estão abertos?'], a: ['No. Some programmes open later, while others may close as places fill. The table shows published dates where available. Check the employer’s programme page before applying.', 'Não. Alguns programas abrem mais tarde e outros podem encerrar à medida que as vagas são preenchidas. A tabela apresenta as datas publicadas, quando disponíveis. Confirma na página do empregador antes de te candidatares.'] },
  { q: ['How recent is the information?', 'Quão recente é a informação?'], a: ['The latest research was completed on 4 October 2026. This is a curated collection, not a live vacancies feed. Employers can change dates and requirements; each programme links to its source.', 'A pesquisa mais recente foi concluída em 4 de outubro de 2026. É uma coleção selecionada, não uma lista de vagas atualizada em tempo real. Os empregadores podem alterar datas e requisitos; cada programa tem uma ligação para a fonte.'] },
  { q: ['Does a listing guarantee visa sponsorship?', 'Uma listagem garante patrocínio de visto?'], a: ['No. Trackr’s sponsorship field describes the company, not necessarily the programme. Check the actual vacancy and your visa conditions. Your university’s international-student team can help; this page is not immigration advice.', 'Não. O campo de patrocínio do Trackr refere-se à empresa, não necessariamente ao programa. Confirma a vaga e as condições do teu visto. A equipa internacional da universidade pode ajudar; esta página não presta aconselhamento de imigração.'], link: 'https://www.gov.uk/skilled-worker-visa/your-job' },
  { q: ['What does rolling recruitment mean?', 'O que significa recrutamento rolling?'], a: ['Applications are reviewed as they arrive. A programme may close once places are filled, even before an advertised deadline. Apply early with a complete, accurate application.', 'As candidaturas são avaliadas à medida que chegam. O programa pode encerrar quando as vagas forem preenchidas, mesmo antes do prazo anunciado. Candidata-te cedo com uma candidatura completa e correta.'] },
  { q: ['Is London the only option?', 'Londres é a única opção?'], a: ['No. Use the location filter to explore places such as Bristol, Birmingham, Edinburgh and Glasgow. The same programme may have different vacancies and requirements by location. A dash means a location was not published in our source.', 'Não. Usa o filtro de localização para explorar cidades como Bristol, Birmingham, Edimburgo e Glasgow. O mesmo programa pode ter vagas e requisitos diferentes por localização. Um traço indica uma localização não publicada na nossa fonte.'] },
  { q: ['Can I use this without an account?', 'Posso usar sem criar conta?'], a: ['Yes. Browse the directory and preparation resources directly. Applications happen on employer websites, which may require registration. There is no personal application-status tracking here.', 'Sim. Consulta diretamente o diretório e os recursos. As candidaturas são feitas nos sites dos empregadores, que podem exigir registo. Não guardamos o estado pessoal das tuas candidaturas aqui.'] },
  { q: ['How do I report a correction?', 'Como posso reportar uma correção?'], a: ['Email 244 Club with the company, programme, link and what needs correcting. You can also suggest an opportunity for a future update.', 'Envia um email ao 244 Club com a empresa, o programa, a ligação e a informação a corrigir. Também podes sugerir oportunidades para uma atualização futura.'], link: 'mailto:club244ao@gmail.com?subject=244%20Tracker%20correction' },
] as const

export const cvTitles = ['CV 101', 'Why your CV matters', 'What makes a good CV', 'Anatomy of a CV', 'How to write strong bullet points', 'Weak to strong', 'Final CV checklist']
